// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwdz0jGwtmlFdmP1dhBIZv-xB5SP01eSg',
    appId: '1:89239913227:web:767a9825fd1cf12aa2d80e',
    messagingSenderId: '89239913227',
    projectId: 'todolistt-8c8ab',
    authDomain: 'todolistt-8c8ab.firebaseapp.com',
    storageBucket: 'todolistt-8c8ab.appspot.com',
    measurementId: 'G-2J47SVDQ1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB44joNsG8sHqGQh-xsmwYCx8E-hdhEWSg',
    appId: '1:89239913227:android:aaf6f9c79abe9b06a2d80e',
    messagingSenderId: '89239913227',
    projectId: 'todolistt-8c8ab',
    storageBucket: 'todolistt-8c8ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD83v0a84ycIrHrMr72C63J_GnrNOwCuwM',
    appId: '1:89239913227:ios:4ef85e8b578225a2a2d80e',
    messagingSenderId: '89239913227',
    projectId: 'todolistt-8c8ab',
    storageBucket: 'todolistt-8c8ab.appspot.com',
    iosBundleId: 'com.example.todolistt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD83v0a84ycIrHrMr72C63J_GnrNOwCuwM',
    appId: '1:89239913227:ios:4ef85e8b578225a2a2d80e',
    messagingSenderId: '89239913227',
    projectId: 'todolistt-8c8ab',
    storageBucket: 'todolistt-8c8ab.appspot.com',
    iosBundleId: 'com.example.todolistt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwdz0jGwtmlFdmP1dhBIZv-xB5SP01eSg',
    appId: '1:89239913227:web:706bf4b8f93c419fa2d80e',
    messagingSenderId: '89239913227',
    projectId: 'todolistt-8c8ab',
    authDomain: 'todolistt-8c8ab.firebaseapp.com',
    storageBucket: 'todolistt-8c8ab.appspot.com',
    measurementId: 'G-GDMJED269T',
  );
}
